### PR TITLE
refactor: streamline DOM test utils

### PR DESCRIPTION
**Pull request by tigt**
Not huge, but hey, less code is best code.

### CODE REVIEW

**Comment by tigt** [comment]
I genuinely don’t know how to interpret the results when I run `ci:test`.

**Comment by DylanPiercey** [comment]
Was there an issue with this? I was planning to take a look and merge tomorrow.

**Comment by tigt** [comment]
@DylanPiercey: I couldn’t understand why the CI was failing, so I closed to be safe rather than sorry. I’ll reopen.

**Comment by DylanPiercey** [comment]
Looks good to me. The SSR tests are a bit flaky and we aren't actively using/checking the CI yet.

**Pull request merged**
